### ISSUE TITLE
INFOGRAFÍA-EDUARDO-7US

### ISSUE THREAD

**Issue by ToniDepp** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-ToniDepp#1]
[INFOGRAFIA-FDGPS-7US.pdf](https://github.com/user-attachments/files/16752857/INFOGRAFIA-FDGPS-7US.pdf)

**Comment by Nelsy21** [comment]
20/20 buen trabajo

**Comment by Nelsy21** [comment]
Redacción y ortografía: 3.33333
Exposición de ideas centrales: 3.3333
Organización de la información: 3.3333
Uso de imagines y colores: 3.3333
Presentación visual: 3.3333
Referencias y presentación: 3.3333

porcentaje final:100%

Calificación final: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
